add diffDataEntryForm
pepfar-datim/data-pack-commons pull request #78
Opened 2023-01-30 19:21 UTC by flopez-bao

- adding function for [DP-856](https://jira.pepfar.net/browse/DP-856) that compares data entry forms that are a result of getSqlView.

2023-02-01 07:20 UTC, sam-bao commented on R/Utility-Functions.R
> +#' @param y a data frame result from a sql view
@flopez-bao Input parameters should be UIDs not data frames. This function should pull the SQL views.

2023-02-07 15:05 UTC, flopez-bao commented on R/Utility-Functions.R
> +#' @param y a data frame result from a sql view
@sam-bao I think the latest changes should suffice. Uids are now params for each sqlview that is called. I added logic for testing purposes to pass manual data if the user wants to. Jason and I have been trying to do this with our testing in datapackr, since it keeps the test more transparent than relying on a mock. Let me know if you see any issues.

2023-02-08 11:55 UTC, sam-bao requested changes
This function is supposed to receive data set uids as input parameters, not SQL view uids.

I have made the necessary changes to the function so that it works as expected, but the tests are now broken. 

I am not convinced that this indirect testing without mocks makes sense. In this case the SQL view returns publicly available metadata, so there wouldn't be anything sensitiv in a mock. However I do not want to contradict any testing strategy being used on datapackr. Adding @jason-p-pickering for his feedback on the tests.

2023-02-08 17:36 UTC, flopez-bao commented
@sam-bao Jason recommended we parse the functions out into two so that my unit test will cover the differentiation between the datasets (diffDataFrames) and then we can cover the top level function (diffDataEntryForm) with a mock. I still need to do the mock, but otherwise the branch is linted and passing .

2023-02-09 12:37 UTC, jason-p-pickering commented on R/Utility-Functions.R
>      stop("in X but not Y could not be calculated because of error ^")
Is a stop worth it here?  Maybe consider to return null if there is an error?

2023-02-09 13:37 UTC, flopez-bao commented on R/Utility-Functions.R
>      stop("in X but not Y could not be calculated because of error ^")
I changed it to return NULL, I think that makes more sense

2023-07-25 11:24 UTC, merged